version: '3'

services:
    proxy:
        container_name: haproxy_server
        build: ./haproxy
        networks:
            - host
        ports:
            - '9000:9000'
            - '6397:10.10.12.111:6397'
            - '6398:10.10.12.111:6398'

networks:
  host:

